In [29]:
import pandas as pd
import numpy as np
from io import StringIO

In [35]:
# --- prices.csv ---
prices_data = StringIO("""
ts,symbol,price
2026-02-20 09:30:00,AAPL,190.00
2026-02-20 09:31:00,AAPL,190.40
2026-02-20 09:32:00,AAPL,189.80
2026-02-20 09:30:00,TSLA,205.00
2026-02-20 09:31:00,TSLA,209.10
2026-02-20 09:32:00,TSLA,206.00
2026-02-20 09:30:00,SPY,500.00
2026-02-20 09:31:00,SPY,499.50
2026-02-20 09:32:00,SPY,499.75
""")

prices = pd.read_csv(prices_data, parse_dates=["ts"])

# --- positions.csv ---
positions_data = StringIO("""
account_id,symbol,qty,avg_cost
1001,AAPL,200,185.00
1001,SPY,-50,505.00
1002,TSLA,30,210.00
1003,AAPL,10,195.00
""")

positions = pd.read_csv(positions_data)

# --- margin.csv ---
margin_data = StringIO("""
symbol,margin_rate
AAPL,0.30
TSLA,0.60
SPY,0.15
""")

margin = pd.read_csv(margin_data)

In [36]:
prices

                   ts symbol   price
0 2026-02-20 09:30:00   AAPL  190.00
1 2026-02-20 09:31:00   AAPL  190.40
2 2026-02-20 09:32:00   AAPL  189.80
3 2026-02-20 09:30:00   TSLA  205.00
4 2026-02-20 09:31:00   TSLA  209.10
5 2026-02-20 09:32:00   TSLA  206.00
6 2026-02-20 09:30:00    SPY  500.00
7 2026-02-20 09:31:00    SPY  499.50
8 2026-02-20 09:32:00    SPY  499.75

In [37]:
prices=prices.sort_values(["symbol","ts"])

In [38]:
prices["log_ret"]=np.log(prices["price"]/prices.groupby("symbol")["price"].shift(1))

In [39]:
prices

                   ts symbol   price   log_ret
0 2026-02-20 09:30:00   AAPL  190.00       NaN
1 2026-02-20 09:31:00   AAPL  190.40  0.002103
2 2026-02-20 09:32:00   AAPL  189.80 -0.003156
6 2026-02-20 09:30:00    SPY  500.00       NaN
7 2026-02-20 09:31:00    SPY  499.50 -0.001001
8 2026-02-20 09:32:00    SPY  499.75  0.000500
3 2026-02-20 09:30:00   TSLA  205.00       NaN
4 2026-02-20 09:31:00   TSLA  209.10  0.019803
5 2026-02-20 09:32:00   TSLA  206.00 -0.014936

In [6]:
positions

   account_id symbol  qty  avg_cost
0        1001   AAPL  200     185.0
1        1001    SPY  -50     505.0
2        1002   TSLA   30     210.0
3        1003   AAPL   10     195.0

In [7]:
margin

  symbol  margin_rate
0   AAPL         0.30
1   TSLA         0.60
2    SPY         0.15